import 'dart:async';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:windows_taskbar/windows_taskbar.dart';

import '../l10n/l10n.dart';
import '../state/app_state.dart';

/// Red badge with the number of unread chats on the Focus taskbar button,
/// like Telegram's. Follows [AppState.badgeFor] for all chats (muted chats
/// do not count); opening a chat in Focus clears its share, Telegram is not
/// told anything.
///
/// Icons come from `assets/badge/` (1…9 and "9+", generated by
/// `tool/make_badges.py`): Windows overlay icons are files, not drawn.
///
/// The count is taken at most once per [delay]: [AppState] notifies on
/// every TDLib update (thousands while chats load), and counting builds the
/// whole chat list, so counting on each one froze the window.
class TaskbarBadge {
  TaskbarBadge(this.state, {this.delay = const Duration(milliseconds: 400)});

  final AppState state;
  final Duration delay;
  int? _shown;
  bool _broken = false;
  Timer? _pending;

  /// How many times the count was taken (tests).
  @visibleForTesting
  int counted = 0;

  void start() {
    state.addListener(_schedule);
    _update();
  }

  void dispose() {
    state.removeListener(_schedule);
    _pending?.cancel();
    _clear();
  }

  void _schedule() {
    if (_broken || _pending != null) return;
    _pending = Timer(delay, () {
      _pending = null;
      _update();
    });
  }

  /// The icon file as the plugin resolves it (next to focus.exe); null when
  /// the assets are not there, which is the case under `flutter test`.
  static String? _iconPath(String name) {
    final sep = Platform.pathSeparator;
    final exeDir = Platform.resolvedExecutable.substring(0, Platform.resolvedExecutable.lastIndexOf(sep));
    final path = '$exeDir${sep}data${sep}flutter_assets${sep}assets${sep}badge$sep$name.ico';
    return File(path).existsSync() ? path : null;
  }

  Future<void> _update() async {
    if (_broken) return;
    counted++;
    final n = state.badgeFor('all');
    if (n == _shown) return;
    _shown = n;
    try {
      if (n == 0) {
        await WindowsTaskbar.resetOverlayIcon();
      } else {
        final name = n > 9 ? 'more' : '$n';
        // No icon files (flutter test): nothing to show, try again later.
        if (_iconPath(name) == null) {
          _shown = null;
          return;
        }
        await WindowsTaskbar.setOverlayIcon(
          ThumbnailToolbarAssetIcon('assets/badge/$name.ico'),
          tooltip: S.current.app.unreadChatsTooltip(n),
        );
      }
    } catch (e) {
      // No taskbar plugin (tests) or Windows refused: stay quiet from now on.
      _broken = true;
      debugPrint('taskbar badge: $e');
    }
  }

  Future<void> _clear() async {
    if (_broken || _shown == null || _shown == 0) return;
    try {
      await WindowsTaskbar.resetOverlayIcon();
    } catch (_) {}
  }
}
